import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import {Alert,Button,Checkbox,Drawer,Empty,Input,Select,Space,Table,Tag,Typography,message as messageService} from 'antd';
import {request} from './bridge';
import type {Workspace} from './schema';
import {DataMergePanel} from './DataMergePanel';
import {dataConclusion,dataLabels,displayValue,exactKey,copyOriginalText,operatorsForType,filterPlaceholder,validFilter,validateDataSettings,sameDataSettings,type DataSettings,type DataField,type DataFilter,type DataResult,type DataRow,type DataTask,type DataValue,type Preparation} from './data';

export type DataHandle={invalidate:()=>void};
const call=async(operation:string,args:object={}):Promise<DataResult>=>{const result=await request(operation,args) as DataResult;if(!result.ok||result.stale)throw new Error(result.error??'数据结果已失效，请重新读取');return result;};
export const DataWorkbench=forwardRef<DataHandle,{workspace:Workspace;disabled:boolean;selected:boolean;beforeRead:()=>Promise<void>;onRunning:(running:boolean)=>void;onMergeRunning?:(running:boolean)=>void}>(function DataWorkbench({workspace,disabled,selected,beforeRead,onRunning,onMergeRunning},ref){
 const [mergeRunning,setMergeRunning]=useState(false);
 const [preparation,setPreparation]=useState<Preparation>();
 const [key,setKey]=useState<string[]>([]),[fields,setFields]=useState<string[]>([]),[filters,setFilters]=useState<DataFilter[]>([]);
 const [draft,setDraft]=useState<DataSettings>(),[draftError,setDraftError]=useState(''),[needsScan,setNeedsScan]=useState(false);
 const [task,setTask]=useState<DataTask>(),[taskId,setTaskId]=useState(''),[browse,setBrowse]=useState(false);
 const [rows,setRows]=useState<DataRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[status,setStatus]=useState('differences'),[side,setSide]=useState('left');
 const [keyInputs,setKeyInputs]=useState<Record<string,string>>({}),[located,setLocated]=useState<string[]>();
 const [detail,setDetail]=useState<DataField[]>(),[detailRow,setDetailRow]=useState<DataRow>(),[changesOnly,setChangesOnly]=useState(true);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[pageError,setPageError]=useState(''),[valueBusy,setValueBusy]=useState('');
 const actionPending=useRef(false);
 const generation=useRef(0),activeId=useRef(''),detailGeneration=useRef(0),pageGeneration=useRef(0);
 const [message,messageHolder]=messageService.useMessage();
 const runningCallback=useRef(onRunning);runningCallback.current=onRunning;const mergeCallback=useRef(onMergeRunning);mergeCallback.current=onMergeRunning;
 useEffect(()=>{runningCallback.current(!!busy||!!taskId&&(!task||task.state==='running'));mergeCallback.current?.(mergeRunning);},[busy,taskId,task,mergeRunning]);
 useEffect(()=>()=>runningCallback.current(false),[]);
 const invalidate=()=>{generation.current++;detailGeneration.current++;pageGeneration.current++;const id=activeId.current;activeId.current='';setTaskId('');setTask(undefined);setRows([]);setTotal(0);setDetail(undefined);setDetailRow(undefined);setLocated(undefined);setPage(1);setBusy('');setDraft(undefined);setError('');setPageError('');const g=generation.current;if(id)void call('data-invalidate',{taskId:id}).catch(e=>{if(g===generation.current)setError(e.message);});};
 useImperativeHandle(ref,()=>({invalidate}));
 useEffect(()=>()=>{generation.current++;detailGeneration.current++;const id=activeId.current;if(id)void call('data-invalidate',{taskId:id}).catch(()=>{});},[]);
 const prepare=async()=>{if(locked||actionPending.current)return;actionPending.current=true;invalidate();setPreparation(undefined);const g=generation.current;setBusy('读取键与字段');try{await beforeRead();if(g!==generation.current)return;const result=await call('data-prepare',{left:workspace.left,right:workspace.right});if(g!==generation.current)return;if(!result.preparation)throw new Error('未收到键与字段');setPreparation(result.preparation);setKey(result.preparation.defaultKey);setFields(result.preparation.defaultFields);setFilters([]);setKeyInputs({});setNeedsScan(false);}catch(e){if(g===generation.current)setError((e as Error).message);}finally{actionPending.current=false;if(g===generation.current)setBusy('');}};
 const start=async()=>{if(locked||actionPending.current||!preparation)return;const invalid=validateDataSettings({key,fields,filters},preparation);if(invalid){setError(invalid);return;}actionPending.current=true;invalidate();setNeedsScan(false);const g=generation.current;setBusy('启动扫描');const browsing=!key.length;setBrowse(browsing);setStatus(browsing?'all':'differences');try{await beforeRead();if(g!==generation.current)return;const result=await call('data-start',{left:workspace.left,right:workspace.right,key,fields,filters,...(browsing?{mode:'browse'}:{})});if(g!==generation.current){if(result.taskId)void call('data-invalidate',{taskId:result.taskId}).catch(()=>{});return;}if(!result.taskId)throw new Error('未收到扫描任务');activeId.current=result.taskId;setTaskId(result.taskId);}catch(e){if(g===generation.current)setError((e as Error).message);}finally{actionPending.current=false;if(g===generation.current)setBusy('');}};
 useEffect(()=>{if(!taskId)return;let disposed=false;let timer:ReturnType<typeof setTimeout>;const g=generation.current;const poll=async()=>{try{const result=await call('data-status',{taskId});if(disposed||g!==generation.current)return;if(!result.task)throw new Error('未收到扫描状态');setTask(result.task);if(result.task.state==='running')timer=setTimeout(()=>void poll(),500);}catch(e){if(!disposed&&g===generation.current){setError((e as Error).message);timer=setTimeout(()=>void poll(),1000);}}};void poll();return()=>{disposed=true;clearTimeout(timer);};},[taskId]);
 useEffect(()=>{if(!taskId||!task?.complete||task.state!=='complete')return;const g=generation.current,p=++pageGeneration.current;setRows([]);setTotal(0);void call('data-page',{taskId,status,offset:(page-1)*30,limit:30,...(located?{key:located}:{}),...(browse?{side}:{})}).then(result=>{if(g===generation.current&&p===pageGeneration.current){setRows(result.rows??[]);setTotal(result.total??0);setPageError('');}}).catch(e=>{if(g===generation.current&&p===pageGeneration.current)setPageError(e.message);});},[taskId,task,page,status,side,located,browse]);
 const openDetail=async(row:DataRow)=>{const g=generation.current,d=++detailGeneration.current;setChangesOnly(true);setDetailRow(row);setDetail(undefined);setValueBusy('');try{const result=await call('data-detail',{taskId,rowId:row.id});if(g===generation.current&&d===detailGeneration.current)setDetail(result.fields??[]);}catch(e){if(g===generation.current&&d===detailGeneration.current){setError((e as Error).message);setDetail([]);}}};
 const fullValue=async(field:DataField,valueSide:'left'|'right',copy:boolean)=>{const initial=field[valueSide];if(!initial||initial.isNull||!detailRow)return;const g=generation.current,d=detailGeneration.current;setValueBusy(`${field.name}:${valueSide}`);try{let value:DataValue={...initial},offset=0,text='';if(initial.truncated){do{const result=await call('data-detail',{taskId,rowId:detailRow.id,field:field.name,side:valueSide,offset,limit:65536});if(g!==generation.current||d!==detailGeneration.current)return;if(!result.value)throw new Error('原值不可用，请重新比对');value=result.value;text+=value.text;if(!value.truncated)break;if(result.nextOffset===undefined||result.nextOffset<=offset)throw new Error('原值分块未前进，请重新比对');offset=result.nextOffset;}while(true);value={...value,text,truncated:false};}if(g!==generation.current||d!==detailGeneration.current)return;setDetail(previous=>previous?.map(item=>item.name===field.name?{...item,[valueSide]:value}:item));if(copy){copyOriginalText(value.text);void message.success(value.encoding==='hex'?'已复制完整 HEX 编码':'已复制完整原文');}}catch(e){if(g===generation.current&&d===detailGeneration.current)setError((e as Error).message);}finally{if(g===generation.current&&d===detailGeneration.current)setValueBusy('');}};
 const running=task?.state==='running';
 const locked=disabled||mergeRunning||!!busy||!!running||!!taskId&&!task;
 const openSettings=()=>{if(locked||actionPending.current)return;setDraft({key:[...key],fields:[...fields],filters:filters.map(filter=>({...filter}))});setDraftError('');};
 const changeFilter=(index:number,patch:Partial<DataFilter>)=>setDraft(previous=>previous&&({...previous,filters:previous.filters.map((filter,i)=>i===index?validFilter({...filter,...patch},preparation?.fields.find(field=>field.name===(patch.field??filter.field))?.type??''):filter)}));
 const applySettings=()=>{
  if(!draft||!preparation||locked||actionPending.current)return;
  const invalid=validateDataSettings(draft,preparation);if(invalid){setDraftError(invalid);return;}
  if(sameDataSettings({key,fields,filters},draft)){setDraft(undefined);return;}
  const next=draft;invalidate();setKey(next.key);setFields(next.fields);setFilters(next.filters);setKeyInputs({});setNeedsScan(true);
 };
 return <div className="data-workbench">{messageHolder}<Space wrap><Typography.Title level={4}>单表数据比对</Typography.Title><Tag>比对只读 · 写入需确认</Tag><Button disabled={locked||!selected} loading={busy==='读取键与字段'} onClick={()=>void prepare()}>读取键与字段</Button></Space>
 {!preparation&&<Typography.Paragraph type="secondary">进入不扫描业务行。先读取键与字段，确认范围后启动；应用新条件后需重新比对。</Typography.Paragraph>}
 {error&&<Alert type="error" showIcon title={error}/>}{pageError&&<Alert type="error" showIcon title={pageError}/>}
 {!preparation?<Empty description={busy||'尚未读取键与字段'}/>:<>
 <div className="data-scope-summary"><Typography.Text strong>生效比对条件</Typography.Text><span>键：{key.join('、')||'无键独立浏览'} · 参与 {fields.length} 个字段</span><Typography.Text>{filters.length?filters.map(filter=>`${filter.field} ${filter.op}${filter.op.includes('NULL')?'':` ${JSON.stringify(filter.value)}`}`).join(' AND '):'无筛选：全表范围'}</Typography.Text><Space wrap><Button disabled={locked} onClick={openSettings}>编辑比对条件</Button><Button type="primary" disabled={locked||!fields.length||!selected} loading={busy==='启动扫描'} onClick={()=>void start()}>{key.length?'开始数据比对':'开始独立浏览'}</Button>{(running||busy==='启动扫描')&&<Button onClick={()=>{if(taskId)void call('data-cancel',{taskId}).catch(e=>setError(e.message));else invalidate();}}>停止扫描</Button>}</Space></div>
 {needsScan&&<Alert type="info" showIcon title="比对条件已应用，旧结果与写入计划已失效，请重新比对。"/>}
 {!key.length&&<Alert type="warning" title="无可靠匹配键 · 左右独立浏览，不推断差异"/>}
 <Drawer title="编辑比对条件 · 未应用草稿" open={!!draft} width={640} onClose={()=>setDraft(undefined)} extra={<Space><Button onClick={()=>setDraft(undefined)}>取消</Button><Button type="primary" disabled={locked} onClick={applySettings}>应用条件</Button></Space>}>
 {draft&&<><Alert type="info" title="取消保留当前结果；应用有效变更后需重新比对。"/>{draftError&&<Alert type="error" title={draftError}/>}
 <div className="data-settings"><label>可靠匹配键<Select aria-label="可靠匹配键" value={JSON.stringify(draft.key)} options={[...preparation.keys.map(item=>({value:JSON.stringify(item.fields),label:`${item.name} (${item.fields.join(', ')})`})),{value:'[]',label:'无键 · 左右分别浏览'}]} onChange={value=>setDraft({...draft,key:JSON.parse(value)})} disabled={locked}/></label>
 <label>参与字段<Select aria-label="参与字段" mode="multiple" value={draft.fields} options={preparation.fields.map(field=>({value:field.name,label:`${field.name} · ${field.type}${field.compatible?'':`（${field.reason??'不兼容'}）`}`,disabled:!field.compatible}))} onChange={fields=>setDraft({...draft,fields})} disabled={locked}/></label></div>
 <Typography.Paragraph type="secondary">未参与：{preparation.fields.filter(field=>!draft.fields.includes(field.name)).map(field=>`${field.name}（${field.compatible?'未选':field.reason??'不兼容'}）`).join('、')||'无'}</Typography.Paragraph>
 <strong>共享 AND 范围</strong>{draft.filters.map((filter,index)=><Space wrap key={index} className="data-filter"><Select aria-label={`筛选字段 ${index+1}`} value={filter.field} options={preparation.fields.filter(field=>field.compatible).map(field=>({value:field.name,label:field.name}))} onChange={field=>changeFilter(index,{field})} disabled={locked}/><Select aria-label={`筛选操作 ${index+1}`} value={filter.op} options={operatorsForType(preparation.fields.find(field=>field.name===filter.field)?.type??'').map(op=>({value:op,label:op}))} onChange={op=>changeFilter(index,{op})} disabled={locked}/>{!filter.op.includes('NULL')&&<Input aria-label={`筛选值 ${index+1}`} value={filter.value} placeholder={filterPlaceholder(preparation.fields.find(field=>field.name===filter.field)?.type??'')} onChange={event=>changeFilter(index,{value:event.target.value})} disabled={locked}/>}<Button disabled={locked} onClick={()=>setDraft({...draft,filters:draft.filters.filter((_,i)=>i!==index)})}>删除条件</Button></Space>)}
 <Button disabled={locked||!preparation.defaultFields.length||draft.filters.length>=32} onClick={()=>setDraft({...draft,filters:[...draft.filters,validFilter({field:preparation.defaultFields[0],op:'=',value:''},preparation.fields.find(field=>field.name===preparation.defaultFields[0])?.type??'')]})}>添加 AND 条件</Button></>}
 </Drawer></>}
 {task&&<><Alert type={task.state==='failed'?'error':task.complete&&!browse?(task.counts.different||task.counts.leftOnly||task.counts.rightOnly?'warning':'success'):'info'} showIcon title={dataConclusion(task,browse)} description={<><div>{dataLabels[task.state]} · {task.phase} · 左已扫描 {task.leftScanned} 行 / 右已扫描 {task.rightScanned} 行 · {task.batches} 批次</div><div>{task.error}</div><details><summary>读取时间与一致性</summary><div>{task.consistency}</div><div>左：{task.leftStartedAt??'未开始'} → {task.leftFinishedAt??'未结束'}；右：{task.rightStartedAt??'未开始'} → {task.rightFinishedAt??'未结束'}</div><div>两端各自快照，不代表全局同一瞬间。</div></details>{!browse&&<div>{task.complete?'最终计数':'暂存计数，缺失结论待两端读完'}：相同 {task.counts.same} / 不同 {task.counts.different} / 仅左 {task.counts.leftOnly} / 仅右 {task.counts.rightOnly}</div>}</>}/>
 <Space wrap className="data-view-controls">{browse?<Select aria-label="独立浏览侧" value={side} onChange={value=>{setSide(value);setPage(1);}} options={[{value:'left',label:'左侧未匹配记录'},{value:'right',label:'右侧未匹配记录'}]}/>:<><Select aria-label="数据状态过滤" value={status} onChange={value=>{setStatus(value);setPage(1);}} options={['differences','different','left-only','right-only','same','all'].map(value=>({value,label:value==='all'?'全部状态':value==='differences'?'全部差异':dataLabels[value]}))}/>{key.map(field=><Input key={field} aria-label={`定位键 ${field}`} placeholder={`完整键 ${field}`} value={keyInputs[field]??''} onChange={event=>setKeyInputs(previous=>({...previous,[field]:event.target.value}))}/>)}<Button onClick={()=>{setLocated(exactKey(keyInputs,key));setPage(1);}}>完整键定位</Button><Button disabled={!located} onClick={()=>{setLocated(undefined);setPage(1);}}>清除定位</Button></>}</Space>
 <Typography.Text type="secondary">当前查看共 {total} 条 · 本页 {rows.length} 条；查看筛选、键定位与分页不缩小写入范围。</Typography.Text>
 <Table<DataRow> rowKey="id" dataSource={rows} pagination={{current:page,pageSize:30,total,showSizeChanger:false,onChange:setPage}} scroll={{x:650,y:360}} locale={{emptyText:'当前页或筛选无匹配记录；整体结论见上方'}} columns={[{title:browse?'浏览标识（不作匹配）':'完整键',render:(_,row)=><pre>{JSON.stringify(row.key)}</pre>},{title:'状态',render:(_,row)=><Tag>{dataLabels[row.status]??row.status}</Tag>},{title:'变化字段',render:(_,row)=>row.changedFields.join('、')||'—'},{title:'详情',render:(_,row)=><Button onClick={()=>void openDetail(row)}>查看左右原值</Button>}]}/></>}
 <DataMergePanel task={task} taskId={taskId} browse={browse} disabled={disabled||!!busy||!!running} onRunning={setMergeRunning} onRecompare={()=>void start()}/>
 <Drawer title={`记录详情 · ${JSON.stringify(detailRow?.key??[])}`} open={!!detailRow} width={900} onClose={()=>{detailGeneration.current++;setDetailRow(undefined);setDetail(undefined);}}>{error&&<Alert type="error" title={error}/>}<Typography.Paragraph type="secondary">{dataLabels[detailRow?.status??'']} · 来自当前扫描结果；关闭后保留筛选、定位与页码。</Typography.Paragraph><Checkbox checked={changesOnly} onChange={event=>setChangesOnly(event.target.checked)}>只看变化字段</Checkbox>{detail===undefined?<Empty description="正在读取扫描结果详情"/>:<Table<DataField> rowKey="name" dataSource={detail.filter(field=>!changesOnly||field.changed||browse)} pagination={false} scroll={{x:700}} locale={{emptyText:'无变化字段；取消勾选可查看全部参与字段'}} columns={[{title:'字段',render:(_,field)=><><strong>{field.name}</strong><div>{field.type}</div>{field.changed&&<Tag color="warning">变化</Tag>}</>},...(['left','right'] as const).map(valueSide=>({title:valueSide==='left'?'左侧原值':'右侧原值',render:(_:unknown,field:DataField)=><div className={field.changed?'changed-property':''}><pre className="data-value" tabIndex={0}>{displayValue(field[valueSide])}</pre>{field[valueSide]&&!field[valueSide]?.isNull&&<Space wrap>{field[valueSide]?.truncated&&<Button size="small" disabled={!!valueBusy} onClick={()=>void fullValue(field,valueSide,false)}>加载完整值</Button>}<Button size="small" disabled={!!valueBusy} loading={valueBusy===`${field.name}:${valueSide}`} onClick={()=>void fullValue(field,valueSide,true)}>{field[valueSide]?.encoding==='hex'?'复制完整 HEX':'复制完整原文'}</Button></Space>}</div>}))]}/>}</Drawer>
 </div>;
});
