import { useEffect, useState } from 'react';
import { Alert, Button, Drawer, Empty, Input, Select, Space, Table, Typography } from 'antd';
import { ExportOutlined, EyeOutlined, RedoOutlined, ReloadOutlined } from '@ant-design/icons';
import { request, type State } from './bridge';
import { filterRecords, isSyncRecord, syncLabels, type SyncRecord } from './sync';
import { SyncOperations, SyncSteps } from './SyncPanel';
import {isMergeRecord,mergeRecordLabels,mergeSummary} from './merge';
import {MergeBatches} from './DataMergePanel';
export function SyncRecords({disabled,onRestore}:{disabled:boolean;onRestore:(state:State)=>void}) {
 const [records,setRecords]=useState<SyncRecord[]>([]);
 const [detail,setDetail]=useState<SyncRecord>();
 const [error,setError]=useState('');
 const [loading,setLoading]=useState(false);
 const [filter,setFilter]=useState({status:'',connection:'',from:'',to:''});
 const report=(e:unknown)=>setError(e instanceof Error?e.message:'记录操作失败');
 const load=async()=>{setLoading(true);try{const result=await request('sync-records');if(!result.ok)throw new Error(result.error ?? '记录读取失败');setRecords(result.records ?? []);setError('');}catch(e){report(e);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const open=async(id:string)=>{try{const result=await request('sync-record',{id});if(!result.ok || !(isSyncRecord(result.record)||isMergeRecord(result.record)))throw new Error(result.error ?? '记录读取失败');setDetail(result.record);}catch(e){report(e);}};
 const restore=async()=>{try{const result=await request('restore-sync-record',{id:detail?.id});if(!result.ok||!result.state)throw new Error(result.error ?? '连接已变化，请重新选择连接与库表');onRestore(result.state);}catch(e){report(e);}};
 return <section className="connections-page"><div className="page-heading"><Typography.Title level={3}>执行记录</Typography.Title><Button icon={<ReloadOutlined />} loading={loading} onClick={()=>void load()}>刷新记录</Button></div>
 <Typography.Paragraph type="secondary">历史记录不代表实时结构或数据。重新比对仅恢复工作台选择，不重放旧计划。</Typography.Paragraph>
 {error && <Alert type="error" title={error} showIcon/>}
 <Space wrap className="schema-filters"><Input aria-label="按连接筛选记录" placeholder="连接名称或标识" value={filter.connection} onChange={e=>setFilter({...filter,connection:e.target.value})}/><Select aria-label="按状态筛选记录" value={filter.status} onChange={status=>setFilter({...filter,status})} options={[{value:'',label:'全部状态'},...['running','passed','failed','stopped','unknown','blocked'].map(value=>({value,label:syncLabels[value]}))]}/><label>开始日期 <Input type="date" aria-label="记录开始日期" value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></label><label>结束日期 <Input type="date" aria-label="记录结束日期" value={filter.to} onChange={e=>setFilter({...filter,to:e.target.value})}/></label></Space>
 <Table<SyncRecord> rowKey="id" dataSource={filterRecords(records,filter)} scroll={{x:800}} locale={{emptyText:<Empty description="无匹配执行记录"/>}} columns={[{title:'开始时间',dataIndex:'startedAt'},{title:'方向 / 配对',render:(_,r)=><>{r.direction==='left-to-right'?'左 → 右':'右 → 左'}<div>{r.left.name} / {r.left.database}.{r.left.table}</div><div>{r.right.name} / {r.right.database}.{r.right.table}</div></>},{title:'模式',render:(_,r)=>isMergeRecord(r)?mergeRecordLabels[r.mode]:'结构同步'},{title:'结果',render:(_,r)=>syncLabels[r.status]},{title:'详情',render:(_,r)=><Button icon={<EyeOutlined />} onClick={()=>void open(r.id)}>查看记录</Button>}]} />
 <Drawer title="执行记录详情" open={!!detail} onClose={()=>setDetail(undefined)} width="min(960px, 96vw)">{detail && <Space orientation="vertical" style={{width:'100%'}}>{error && <Alert type="error" title={error} showIcon/>}<strong>{syncLabels[detail.status]} · {detail.startedAt} — {detail.finishedAt ?? '未结束'}</strong><span>{detail.left.name} / {detail.left.database}.{detail.left.table} {detail.direction==='left-to-right'?'→':'←'} {detail.right.name} / {detail.right.database}.{detail.right.table}</span><Space wrap><Button icon={<RedoOutlined />} disabled={disabled} onClick={()=>void restore()}>回到工作台重新比对</Button><Button icon={<ExportOutlined />} onClick={()=>{void request('export-sync-record',{id:detail.id}).then(result=>{if(!result.ok)throw new Error(result.error ?? '导出失败');}).catch(report);}}>导出记录 JSON</Button></Space>{detail.storageWarning && <Alert type="warning" showIcon title="记录保存异常" description={detail.storageWarning}/>} {detail.error && <Alert type="warning" title={detail.error}/>}{isMergeRecord(detail)?<><strong>已确认提交 {detail.committed} / {detail.total} · {mergeRecordLabels[detail.mode]}</strong>{detail.counts&&<span>{mergeSummary({counts:detail.counts})}</span>}<MergeBatches batches={detail.batches}/><Typography.Text type="secondary">批次结果不代表数据已完全一致。返回工作台后选择“数据比对”，读取键与字段并确认范围，再重新比对。</Typography.Text></>:<><SyncOperations plan={detail}/><SyncSteps steps={detail.steps}/></>}{!isMergeRecord(detail)&&detail.verification && <Alert type="info" title={`结构复核：${syncLabels[detail.verification.status] ?? detail.verification.status}`} description={detail.verification.error}/>}{!isMergeRecord(detail)&&<><Typography.Title level={5}>完整 SQL</Typography.Title><pre className="sync-sql" tabIndex={0}>{detail.sql}</pre><Typography.Title level={5}>两端原始结构定义</Typography.Title><Typography.Text type="secondary">仅结构定义，不含业务数据，不能恢复已删除数据。</Typography.Text><pre className="sync-sql" tabIndex={0}>{JSON.stringify(detail.snapshots ?? {},null,2)}</pre></>}</Space>}</Drawer>
 </section>;
}
